export const ConditionalPaymentABI = [
    "constructor(address _usdc)",
    "error DeadlineExpired()",
    "error DeadlineNotExpired()",
    "error InvalidAddress()",
    "error InvalidAmount()",
    "error InvalidDeadline()",
    "error InvalidStatus()",
    "error NotAuthorized()",
    "error PaymentNotFound()",
    "event PaymentAccepted(uint256 indexed paymentId, address indexed worker)",
    "event PaymentCreated(uint256 indexed paymentId, address indexed principal, address indexed verifier, uint256 amount, bytes32 conditionHash, uint256 deadline)",
    "event PaymentRefunded(uint256 indexed paymentId, address indexed principal, uint256 amount)",
    "event PaymentReleased(uint256 indexed paymentId, address indexed worker, uint256 amount)",
    "event PaymentVerified(uint256 indexed paymentId, bool approved)",
    "event ProofSubmitted(uint256 indexed paymentId, bytes32 proofHash)",
    "function acceptPayment(uint256 paymentId)",
    "function cancelPayment(uint256 paymentId)",
    "function createPayment(uint256 amount, bytes32 conditionHash, address verifier, uint256 deadline) returns (uint256 paymentId)",
    "function getPayment(uint256 paymentId) view returns (tuple(uint256 id, address principal, address worker, address verifier, uint256 amount, bytes32 conditionHash, uint8 status, uint256 createdAt, uint256 deadline))",
    "function paymentCounter() view returns (uint256)",
    "function payments(uint256) view returns (uint256 id, address principal, address worker, address verifier, uint256 amount, bytes32 conditionHash, uint8 status, uint256 createdAt, uint256 deadline)",
    "function refundOnTimeout(uint256 paymentId)",
    "function submitProof(uint256 paymentId, bytes32 proofHash)",
    "function usdc() view returns (address)",
    "function verify(uint256 paymentId, bool approved)"
];
